services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard_the_band
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    env_file:
      - .env
    
  db:
    image: postgres:15
    container_name: dashboard_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
  redis:
    image: redis:7
    container_name: dashboard_redis
    ports:
      - "6379:6379"
    restart: always
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard_celery
    command: celery -A dashboard worker --loglevel=info
    volumes:
      - ./src:/app/src
    depends_on:
      - app
      - redis
    env_file:
      - .env

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard_celery_beat
    command: celery -A dashboard beat --loglevel=info
    volumes:
      - ./src:/app/src
    depends_on:
      - app
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
