version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard_the_band
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    
  db:
    image: postgres:15
    container_name: dashboard_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env

volumes:
  postgres_data:
